INSERT INTO "Card" (
      "tcgId", "name", "supertype", "subtypes", "types", "hp", 
      "retreatCost", "number", "artist", "rarity", "flavorText", 
      "setId", "setName", "setSeries", "setPrintedTotal", "setTotal", 
      "setReleaseDate", "imageSmall", "imageLarge", "nationalPokedexNumbers", 
      "rules", "abilities", "attacks", "weaknesses", "resistances",
      "standardLegal", "expandedLegal", "unlimitedLegal"
    ) VALUES (
          'dp3-1',
          'Ampharos',
          'Pokémon',
          '{"Stage 2"}',
          '{"Lightning"}',
          130,
          '{"Colorless","Colorless","Colorless"}',
          '1',
          'Kouki Saitou',
          'Rare Holo',
          'The tip of its tail shines brightly. In the olden days, people sent signals using the tail''s light.',
          'dp3',
          'Secret Wonders',
          'Diamond & Pearl',
          132,
          132,
          '2007/11/01',
          'https://images.pokemontcg.io/dp3/1.png',
          'https://images.pokemontcg.io/dp3/1_hires.png',
          '{181}',
          '{}',
          '[{"name":"Jamming","text":"After your opponent plays a Supporter card from his or her hand, put 1 damage counter on each of your opponent''s Pokémon. You can''t use more than 1 Jamming Poké-Body each turn.","type":"Poké-Body"}]'::jsonb[],
          '[{"name":"Cluster Bolt","cost":["Lightning","Colorless","Colorless"],"convertedEnergyCost":3,"damage":"70","text":"You may discard all Lightning Energy attached to Ampharos. If you do, this attack does 20 damage to each of your opponent''s Benched Pokémon that has any Energy cards attached to it. (Don''t apply Weakness and Resistance for Benched Pokémon.)"}]'::jsonb[],
          '[{"type":"Fighting","value":"+30"}]'::jsonb[],
          '[{"type":"Metal","value":"-20"}]'::jsonb[],
          false,
          false,
          true
        ),
(
          'ex12-1',
          'Aerodactyl',
          'Pokémon',
          '{"Stage 1"}',
          '{"Colorless"}',
          70,
          '{}',
          '1',
          'Hajime Kusajima',
          'Rare Holo',
          NULL,
          'ex12',
          'Legend Maker',
          'EX',
          92,
          93,
          '2006/02/01',
          'https://images.pokemontcg.io/ex12/1.png',
          'https://images.pokemontcg.io/ex12/1_hires.png',
          '{142}',
          '{}',
          '[{"name":"Reactive Protection","text":"Any damage done to Aerodactyl by attacks from your opponent''s Pokémon is reduced by 10 for each React Energy card attached to Aerodactyl (after applying Weakness and Resistance).","type":"Poké-Body"}]'::jsonb[],
          '[{"name":"Power Blow","cost":["Colorless"],"convertedEnergyCost":1,"damage":"10+","text":"Does 10 damage plus 10 more damage for each Energy attached to Aerodactyl."},{"name":"Speed Stroke","cost":["Colorless","Colorless","Colorless"],"convertedEnergyCost":3,"damage":"40","text":"During your opponent''s next turn, prevent all effects, including damage, done to Aerodactyl by attacks from your opponent''s Pokémon-ex."}]'::jsonb[],
          '[{"type":"Lightning","value":"×2"}]'::jsonb[],
          '[{"type":"Fighting","value":"-30"}]'::jsonb[],
          false,
          false,
          true
        ),
(
          'mcd19-1',
          'Caterpie',
          'Pokémon',
          '{"Basic"}',
          '{"Grass"}',
          50,
          '{"Colorless"}',
          '1',
          'Sekio',
          NULL,
          'When attacked by bird Pokémon, it resists by releasing a terrifically strong odor from its antennae, but it often becomes their prey.',
          'mcd19',
          'McDonald''s Collection 2019',
          'Other',
          12,
          12,
          '2019/10/15',
          'https://images.pokemontcg.io/mcd19/1.png',
          'https://images.pokemontcg.io/mcd19/1_hires.png',
          '{10}',
          '{}',
          '[]'::jsonb[],
          '[{"cost":["Grass"],"name":"Surprise Attack","text":"Flip a coin. If tails, this attack does nothing.","damage":"20","convertedEnergyCost":1}]'::jsonb[],
          '[{"type":"Fire","value":"×2"}]'::jsonb[],
          '[]'::jsonb[],
          false,
          true,
          true
        ),
(
          'ex7-1',
          'Azumarill',
          'Pokémon',
          '{"Stage 1"}',
          '{"Water"}',
          80,
          '{"Colorless"}',
          '1',
          'Sumiyoshi Kizuki',
          'Rare Holo',
          NULL,
          'ex7',
          'Team Rocket Returns',
          'EX',
          109,
          111,
          '2004/11/01',
          'https://images.pokemontcg.io/ex7/1.png',
          'https://images.pokemontcg.io/ex7/1_hires.png',
          '{184}',
          '{}',
          '[{"name":"Froth","text":"Once during your turn, when you play Azumarill from your hand to evolve 1 of your Active Pokémon, you may use this power. Each Defending Pokémon is now Paralyzed.","type":"Poké-Power"}]'::jsonb[],
          '[{"name":"Water Punch","cost":["Water","Colorless"],"convertedEnergyCost":2,"damage":"20+","text":"Flip a coin for each Water Energy attached to Azumarill. This attack does 20 damage plus 20 more damage for each heads."}]'::jsonb[],
          '[{"type":"Lightning","value":"×2"}]'::jsonb[],
          '[]'::jsonb[],
          false,
          false,
          true
        ),
(
          'sm9-1',
          'Celebi & Venusaur-GX',
          'Pokémon',
          '{"Basic","TAG TEAM","GX"}',
          '{"Grass"}',
          270,
          '{"Colorless","Colorless","Colorless","Colorless"}',
          '1',
          'Mitsuhiro Arita',
          'Rare Holo GX',
          NULL,
          'sm9',
          'Team Up',
          'Sun & Moon',
          181,
          198,
          '2019/02/01',
          'https://images.pokemontcg.io/sm9/1.png',
          'https://images.pokemontcg.io/sm9/1_hires.png',
          '{3,251}',
          '{"TAG TEAM rule: When your TAG TEAM is Knocked Out, your opponent takes 3 Prize cards."}',
          '[]'::jsonb[],
          '[{"name":"Pollen Hazard","cost":["Grass","Colorless","Colorless"],"convertedEnergyCost":3,"damage":"50","text":"Your opponent''s Active Pokémon is now Burned, Confused, and Poisoned."},{"name":"Solar Beam","cost":["Grass","Grass","Colorless","Colorless"],"convertedEnergyCost":4,"damage":"150","text":""},{"name":"Evergreen-GX","cost":["Grass","Grass","Colorless","Colorless"],"convertedEnergyCost":4,"damage":"180","text":"Heal all damage from this Pokémon. If this Pokémon has at least 1 extra Grass Energy attached to it (in addition to this attack''s cost), shuffle all cards from your discard pile into your deck. (You can''t use more than 1 GX attack in a game.)"}]'::jsonb[],
          '[{"type":"Fire","value":"×2"}]'::jsonb[],
          '[]'::jsonb[],
          false,
          true,
          true
        ),
(
          'pl1-2',
          'Blastoise',
          'Pokémon',
          '{"Stage 2"}',
          '{"Water"}',
          130,
          '{"Colorless","Colorless"}',
          '2',
          'Kagemaru Himeno',
          'Rare Holo',
          NULL,
          'pl1',
          'Platinum',
          'Platinum',
          127,
          133,
          '2009/02/11',
          'https://images.pokemontcg.io/pl1/2.png',
          'https://images.pokemontcg.io/pl1/2_hires.png',
          '{9}',
          '{}',
          '[{"name":"Dig Well","text":"Once during your turn (before your attack), you may look at the top 3 cards of your deck, choose as many Water Energy cards as you like, and attach them to your Pokémon in any way you like. Discard the other cards. This power can''t be used if Blastoise is affected by a Special Condition.","type":"Poké-Power"}]'::jsonb[],
          '[{"name":"Aqua Press","cost":["Water","Colorless"],"convertedEnergyCost":2,"damage":"20+","text":"Does 20 damage plus 10 more damage for each Energy attached to all Pokémon (both yours and your opponent''s)."},{"name":"Double Launcher","cost":["Water","Water","Colorless","Colorless"],"convertedEnergyCost":4,"damage":"","text":"Discard 2 Energy attached to Blastoise. Choose 2 of your opponent''s Benched Pokémon. This attack does 60 damage to each of them. (Don''t apply Weakness and Resistance for Benched Pokémon.) Blastoise can''t use Double Launcher during your next turn."}]'::jsonb[],
          '[{"type":"Lightning","value":"+30"}]'::jsonb[],
          '[]'::jsonb[],
          false,
          false,
          true
        ),
(
          'ex3-2',
          'Altaria',
          'Pokémon',
          '{"Stage 1"}',
          '{"Colorless"}',
          80,
          '{"Colorless"}',
          '2',
          'Atsuko Nishida',
          'Rare Holo',
          NULL,
          'ex3',
          'Dragon',
          'EX',
          97,
          100,
          '2003/11/24',
          'https://images.pokemontcg.io/ex3/2.png',
          'https://images.pokemontcg.io/ex3/2_hires.png',
          '{334}',
          '{}',
          '[]'::jsonb[],
          '[{"name":"Dragon Dance","cost":["Colorless"],"convertedEnergyCost":1,"damage":"","text":"During your next turn, if any of your current Active Pokémon does damage to any Defending Pokémon, this attack does 40 more damage (before applying Weakness and Resistance)."},{"name":"Dragon Song","cost":["Water","Lightning"],"convertedEnergyCost":2,"damage":"30","text":"Each Defending Pokémon is now Asleep."}]'::jsonb[],
          '[{"type":"Colorless","value":"×2"}]'::jsonb[],
          '[{"type":"Grass","value":"-30"},{"type":"Fighting","value":"-30"}]'::jsonb[],
          false,
          false,
          true
        ),
(
          'sm9-2',
          'Weedle',
          'Pokémon',
          '{"Basic"}',
          '{"Grass"}',
          40,
          '{"Colorless"}',
          '2',
          'Shibuzoh.',
          'Common',
          'Often found in forests and grasslands. It has a sharp, toxic barb of around two inches on top of its head.',
          'sm9',
          'Team Up',
          'Sun & Moon',
          181,
          198,
          '2019/02/01',
          'https://images.pokemontcg.io/sm9/2.png',
          'https://images.pokemontcg.io/sm9/2_hires.png',
          '{13}',
          '{}',
          '[]'::jsonb[],
          '[{"name":"Tangle Drag","cost":["Grass"],"convertedEnergyCost":1,"damage":"","text":"Switch 1 of your opponent''s Benched Pokémon with their Active Pokémon."},{"name":"Bug Bite","cost":["Grass"],"convertedEnergyCost":1,"damage":"10","text":""}]'::jsonb[],
          '[{"type":"Fire","value":"×2"}]'::jsonb[],
          '[]'::jsonb[],
          false,
          true,
          true
        ),
(
          'mcd19-2',
          'Alolan Exeggutor',
          'Pokémon',
          '{"Stage 1"}',
          '{"Grass"}',
          160,
          '{"Colorless","Colorless","Colorless"}',
          '2',
          'Satoshi Shirai',
          NULL,
          'As it grew taller and taller, it outgrew its reliance on psychic powers, while within it awakened the power of the sleeping dragon.',
          'mcd19',
          'McDonald''s Collection 2019',
          'Other',
          12,
          12,
          '2019/10/15',
          'https://images.pokemontcg.io/mcd19/2.png',
          'https://images.pokemontcg.io/mcd19/2_hires.png',
          '{103}',
          '{}',
          '[]'::jsonb[],
          '[{"cost":["Grass"],"name":"Tropical Shake","text":"This attack does 20 more damage for each type of basic Energy card in your discard pile. You can''t add more than 100 damage in this way.","damage":"20+","convertedEnergyCost":1}]'::jsonb[],
          '[{"type":"Fire","value":"×2"}]'::jsonb[],
          '[]'::jsonb[],
          false,
          true,
          true
        ),
(
          'xy5-2',
          'Kakuna',
          'Pokémon',
          '{"Stage 1"}',
          '{"Grass"}',
          80,
          '{"Colorless","Colorless","Colorless"}',
          '2',
          'Kagemaru Himeno',
          'Uncommon',
          'While awaiting evolution, it hides from predators under leaves and in nooks of branches.',
          'xy5',
          'Primal Clash',
          'XY',
          160,
          164,
          '2015/02/04',
          'https://images.pokemontcg.io/xy5/2.png',
          'https://images.pokemontcg.io/xy5/2_hires.png',
          '{14}',
          '{}',
          '[]'::jsonb[],
          '[{"name":"Bug Bite","cost":["Grass"],"convertedEnergyCost":1,"damage":"20","text":""}]'::jsonb[],
          '[{"type":"Fire","value":"×2"}]'::jsonb[],
          '[]'::jsonb[],
          false,
          true,
          true
        ),
(
          'sm12-1',
          'Venusaur & Snivy-GX',
          'Pokémon',
          '{"Basic","TAG TEAM","GX"}',
          '{"Grass"}',
          270,
          '{"Colorless","Colorless","Colorless"}',
          '1',
          'Mitsuhiro Arita',
          'Rare Holo GX',
          NULL,
          'sm12',
          'Cosmic Eclipse',
          'Sun & Moon',
          236,
          272,
          '2019/11/01',
          'https://images.pokemontcg.io/sm12/1.png',
          'https://images.pokemontcg.io/sm12/1_hires.png',
          '{3,495}',
          '{"TAG TEAM rule: When your TAG TEAM is Knocked Out, your opponent takes 3 Prize cards."}',
          '[{"name":"Shining Vine","text":"Once during your turn, if this Pokémon is your Active Pokémon, when you attach a Grass Energy card from your hand to it, you may switch 1 of your opponent''s Benched Pokémon with their Active Pokémon.","type":"Ability"}]'::jsonb[],
          '[{"name":"Forest Dump","cost":["Grass","Colorless","Colorless","Colorless"],"convertedEnergyCost":4,"damage":"160","text":""},{"name":"Solar Plant-GX","cost":["Colorless","Colorless","Colorless"],"convertedEnergyCost":3,"damage":"","text":"This attack does 50 damage to each of your opponent''s Pokémon. If this Pokémon has at least 2 extra Energy attached to it (in addition to this attack''s cost), heal all damage from all of your Pokémon. (Don''t apply Weakness and Resistance for Benched Pokémon.) (You can''t use more than 1 GX attack in a game.)"}]'::jsonb[],
          '[{"type":"Fire","value":"×2"}]'::jsonb[],
          '[]'::jsonb[],
          false,
          true,
          true
        ),
(
          'si1-1',
          'Mew',
          'Pokémon',
          '{"Basic"}',
          '{"Psychic"}',
          30,
          '{}',
          '1',
          'Keiko Fukuyama',
          NULL,
          'This Pokémon''s body is covered by fine hairs that can be seen only under a microscope.',
          'si1',
          'Southern Islands',
          'Other',
          18,
          18,
          '2001/07/31',
          'https://images.pokemontcg.io/si1/1.png',
          'https://images.pokemontcg.io/si1/1_hires.png',
          '{151}',
          '{}',
          '[]'::jsonb[],
          '[{"name":"Rainbow Wave","cost":["Psychic"],"convertedEnergyCost":1,"damage":"","text":"Choose a type of Energy other than Colorless attached to Mew. This attack does 20 damage to each of your opponent''s Pokémon of that type (including Benched Pokémon). Don''t apply Weakness and Resistance."}]'::jsonb[],
          '[{"type":"Psychic","value":"×2"}]'::jsonb[],
          '[]'::jsonb[],
          false,
          false,
          true
        ),
(
          'sm3-1',
          'Caterpie',
          'Pokémon',
          '{"Basic"}',
          '{"Grass"}',
          50,
          '{"Colorless"}',
          '1',
          'Sekio',
          'Common',
          'When attacked by bird Pokémon, it resists by releasing a terrifically strong odor from its antennae, but it often becomes their prey.',
          'sm3',
          'Burning Shadows',
          'Sun & Moon',
          147,
          177,
          '2017/08/05',
          'https://images.pokemontcg.io/sm3/1.png',
          'https://images.pokemontcg.io/sm3/1_hires.png',
          '{10}',
          '{}',
          '[]'::jsonb[],
          '[{"name":"Surprise Attack","cost":["Grass"],"convertedEnergyCost":1,"damage":"20","text":"Flip a coin. If tails, this attack does nothing."}]'::jsonb[],
          '[{"type":"Fire","value":"×2"}]'::jsonb[],
          '[]'::jsonb[],
          false,
          true,
          true
        ),
(
          'pop7-1',
          'Ampharos',
          'Pokémon',
          '{"Stage 2"}',
          '{"Lightning"}',
          130,
          '{"Colorless","Colorless","Colorless"}',
          '1',
          'Kouki Saitou',
          'Rare',
          'The tip of its tail shines brightly. In the olden days, people sent signals using the tail''s light.',
          'pop7',
          'POP Series 7',
          'POP',
          17,
          17,
          '2008/03/01',
          'https://images.pokemontcg.io/pop7/1.png',
          'https://images.pokemontcg.io/pop7/1_hires.png',
          '{181}',
          '{}',
          '[{"name":"Jamming","text":"After your opponent plays a Supporter card from his or her hand, put 1 damage counter on each of your opponent''s Pokémon. You can''t use more than 1 Jamming Poké-Body each turn.","type":"Poké-Body"}]'::jsonb[],
          '[{"name":"Cluster Bolt","cost":["Lightning","Colorless","Colorless"],"convertedEnergyCost":3,"damage":"70","text":"You may discard all Lightning Energy attached to Ampharos. If you do, this attack does 20 damage to each of your opponent''s Benched Pokémon that has any Energy cards attached to it. (Don''t apply Weakness and Resistance for Benched Pokémon.)"}]'::jsonb[],
          '[{"type":"Fighting","value":"+30"}]'::jsonb[],
          '[{"type":"Metal","value":"-20"}]'::jsonb[],
          false,
          false,
          true
        ),
(
          'bw1-2',
          'Snivy',
          'Pokémon',
          '{"Basic"}',
          '{"Grass"}',
          60,
          '{"Colorless"}',
          '2',
          '5ban Graphics',
          'Common',
          'They photosynthesize by bathing their tails in sunlight. When they are not feeling well, their tails droop.',
          'bw1',
          'Black & White',
          'Black & White',
          114,
          115,
          '2011/04/25',
          'https://images.pokemontcg.io/bw1/2.png',
          'https://images.pokemontcg.io/bw1/2_hires.png',
          '{495}',
          '{}',
          '[]'::jsonb[],
          '[{"name":"Leaf Blade","cost":["Grass","Colorless"],"convertedEnergyCost":2,"damage":"10+","text":"Flip a coin. If heads, this attack does 30 more damage."}]'::jsonb[],
          '[{"type":"Fire","value":"×2"}]'::jsonb[],
          '[{"type":"Water","value":"-20"}]'::jsonb[],
          false,
          true,
          true
        ),
(
          'base4-3',
          'Chansey',
          'Pokémon',
          '{"Basic"}',
          '{"Colorless"}',
          120,
          '{"Colorless"}',
          '3',
          'Ken Sugimori',
          'Rare Holo',
          'A rare and elusive Pokémon that is said to bring happiness to those who manage to catch it.',
          'base4',
          'Base Set 2',
          'Base',
          130,
          130,
          '2000/02/24',
          'https://images.pokemontcg.io/base4/3.png',
          'https://images.pokemontcg.io/base4/3_hires.png',
          '{113}',
          '{}',
          '[]'::jsonb[],
          '[{"name":"Scrunch","cost":["Colorless","Colorless"],"convertedEnergyCost":2,"damage":"","text":"Flip a coin. If heads, prevent all damage done to Chansey during your opponent''s next turn. (Any other effects of attacks still happen.)"},{"name":"Double-edge","cost":["Colorless","Colorless","Colorless","Colorless"],"convertedEnergyCost":4,"damage":"80","text":"Chansey does 80 damage to itself."}]'::jsonb[],
          '[{"type":"Fighting","value":"×2"}]'::jsonb[],
          '[{"type":"Psychic","value":"-30"}]'::jsonb[],
          false,
          false,
          true
        ),
(
          'hgss4-3',
          'Celebi',
          'Pokémon',
          '{"Basic"}',
          '{"Psychic"}',
          70,
          '{"Colorless"}',
          '3',
          'Shin Nagasawa',
          'Rare Holo',
          'This Pokémon wanders across time. Grass and trees flourish in the forests in which it has appeared.',
          'hgss4',
          'HS—Triumphant',
          'HeartGold & SoulSilver',
          102,
          103,
          '2010/11/03',
          'https://images.pokemontcg.io/hgss4/3.png',
          'https://images.pokemontcg.io/hgss4/3_hires.png',
          '{251}',
          '{}',
          '[]'::jsonb[],
          '[{"name":"Future Sight","cost":["Psychic"],"convertedEnergyCost":1,"damage":"","text":"Look at the top 5 cards of either player''s deck and put them back on top of that player''s deck in any order."},{"name":"Leaf Bind","cost":["Grass","Colorless"],"convertedEnergyCost":2,"damage":"30","text":"Flip a coin. If heads, the Defending Pokémon is now Paralyzed."}]'::jsonb[],
          '[{"type":"Psychic","value":"×2"}]'::jsonb[],
          '[]'::jsonb[],
          false,
          false,
          true
        ),
(
          'ex7-3',
          'Dark Crobat',
          'Pokémon',
          '{"Stage 2"}',
          '{"Grass","Darkness"}',
          90,
          '{"Colorless"}',
          '3',
          'Kyoko Koizumi',
          'Rare Holo',
          NULL,
          'ex7',
          'Team Rocket Returns',
          'EX',
          109,
          111,
          '2004/11/01',
          'https://images.pokemontcg.io/ex7/3.png',
          'https://images.pokemontcg.io/ex7/3_hires.png',
          '{169}',
          '{"This Pokémon is both Grass Darkness type."}',
          '[{"name":"Black Beam","text":"Once during your turn (before your attack), if Dark Crobat is your Active Pokémon, you may choose 1 of the Defending Pokémon. That Pokémon is now Poisoned. This power can''t be used if Dark Crobat is affected by a Special Condition.","type":"Poké-Power"}]'::jsonb[],
          '[{"name":"Dark Drain","cost":["Grass","Colorless"],"convertedEnergyCost":2,"damage":"","text":"Does 10 damage to each of your opponent''s Pokémon. (Don''t apply Weakness and Resistance for Benched Pokémon.) Remove from Dark Crobat a number of damage counters equal to the number of your opponent''s Pokémon in play."},{"name":"Skill Dive","cost":["Grass","Colorless"],"convertedEnergyCost":2,"damage":"","text":"Does 30 damage to 1 of your opponent''s Pokémon. (Don''t apply Weakness and Resistance for Benched Pokémon.)"}]'::jsonb[],
          '[{"type":"Lightning","value":"×2"}]'::jsonb[],
          '[{"type":"Fighting","value":"-30"}]'::jsonb[],
          false,
          false,
          true
        ),
(
          'swsh35-2',
          'Weedle',
          'Pokémon',
          '{"Basic"}',
          '{"Grass"}',
          60,
          '{"Colorless"}',
          '2',
          'Yuka Morii',
          'Common',
          'Its poison stinger is very powerful. Its bright-colored body is intended to warn off its enemies.',
          'swsh35',
          'Champion''s Path',
          'Sword & Shield',
          73,
          80,
          '2020/09/25',
          'https://images.pokemontcg.io/swsh35/2.png',
          'https://images.pokemontcg.io/swsh35/2_hires.png',
          '{13}',
          '{}',
          '[]'::jsonb[],
          '[{"name":"Call for Family","cost":["Colorless"],"convertedEnergyCost":1,"damage":"","text":"Search your deck for a Basic Pokémon and put it onto your Bench. Then, shuffle your deck."}]'::jsonb[],
          '[{"type":"Fire","value":"×2"}]'::jsonb[],
          '[]'::jsonb[],
          false,
          true,
          true
        ),
(
          'xy2-3',
          'Butterfree',
          'Pokémon',
          '{"Stage 2"}',
          '{"Grass"}',
          130,
          '{"Colorless"}',
          '3',
          'sui',
          'Rare',
          'It loves the honey of flowers and can locate flower patches that have even tiny amounts of pollen.',
          'xy2',
          'Flashfire',
          'XY',
          106,
          110,
          '2014/05/07',
          'https://images.pokemontcg.io/xy2/3.png',
          'https://images.pokemontcg.io/xy2/3_hires.png',
          '{12}',
          '{}',
          '[]'::jsonb[],
          '[{"name":"Quiver Dance","cost":["Grass"],"convertedEnergyCost":1,"damage":"","text":"Search your deck for a basic Energy card and attach it to this Pokémon. Shuffle your deck afterward. If you attached Energy in this way, heal 40 damage from this Pokémon."},{"name":"Gust","cost":["Grass","Colorless","Colorless"],"convertedEnergyCost":3,"damage":"70","text":""}]'::jsonb[],
          '[{"type":"Lightning","value":"×2"}]'::jsonb[],
          '[{"type":"Fighting","value":"-20"}]'::jsonb[],
          false,
          true,
          true
        ),
(
          'sm9-3',
          'Weedle',
          'Pokémon',
          '{"Basic"}',
          '{"Grass"}',
          50,
          '{"Colorless"}',
          '3',
          'SATOSHI NAKAI',
          'Common',
          'Often found in forests and grasslands. It has a sharp, toxic barb of around two inches on top of its head.',
          'sm9',
          'Team Up',
          'Sun & Moon',
          181,
          198,
          '2019/02/01',
          'https://images.pokemontcg.io/sm9/3.png',
          'https://images.pokemontcg.io/sm9/3_hires.png',
          '{13}',
          '{}',
          '[]'::jsonb[],
          '[{"name":"Reckless Charge","cost":["Colorless"],"convertedEnergyCost":1,"damage":"20","text":"This Pokémon does 10 damage to itself."}]'::jsonb[],
          '[{"type":"Fire","value":"×2"}]'::jsonb[],
          '[]'::jsonb[],
          false,
          true,
          true
        ),
(
          'sm1-2',
          'Metapod',
          'Pokémon',
          '{"Stage 1"}',
          '{"Grass"}',
          80,
          '{"Colorless","Colorless","Colorless"}',
          '2',
          'Yuka Morii',
          'Uncommon',
          'Its shell is filled with its soft innards. It doesn''t move much because of the risk it might carelessly spill its innards out.',
          'sm1',
          'Sun & Moon',
          'Sun & Moon',
          149,
          173,
          '2017/02/03',
          'https://images.pokemontcg.io/sm1/2.png',
          'https://images.pokemontcg.io/sm1/2_hires.png',
          '{11}',
          '{}',
          '[]'::jsonb[],
          '[{"name":"Iron Defense","cost":["Colorless"],"convertedEnergyCost":1,"damage":"","text":"Flip a coin. If heads, prevent all damage done to this Pokémon by attacks during your opponent''s next turn."},{"name":"Bug Bite","cost":["Colorless","Colorless","Colorless"],"convertedEnergyCost":3,"damage":"40","text":""}]'::jsonb[],
          '[{"type":"Fire","value":"×2"}]'::jsonb[],
          '[]'::jsonb[],
          false,
          true,
          true
        ),
(
          'mcd19-3',
          'Magmar',
          'Pokémon',
          '{"Basic"}',
          '{"Fire"}',
          80,
          '{"Colorless","Colorless"}',
          '3',
          'Yumi',
          NULL,
          'When angered, it spouts brilliant fire from all over its body. It doesn''t calm down until its opponent has burned to ash.',
          'mcd19',
          'McDonald''s Collection 2019',
          'Other',
          12,
          12,
          '2019/10/15',
          'https://images.pokemontcg.io/mcd19/3.png',
          'https://images.pokemontcg.io/mcd19/3_hires.png',
          '{126}',
          '{}',
          '[]'::jsonb[],
          '[{"cost":["Fire"],"name":"Controlled Burn","text":"Discard the top card of your opponent''s deck.","damage":"","convertedEnergyCost":1},{"cost":["Fire","Fire","Colorless"],"name":"Flamethrower","text":"Discard an Energy from this Pokémon.","damage":"80","convertedEnergyCost":3}]'::jsonb[],
          '[{"type":"Water","value":"×2"}]'::jsonb[],
          '[]'::jsonb[],
          false,
          true,
          true
        ),
(
          'dp3-3',
          'Charizard',
          'Pokémon',
          '{"Stage 2"}',
          '{"Fire"}',
          130,
          '{"Colorless","Colorless","Colorless"}',
          '3',
          'Daisuke Ito',
          'Rare Holo',
          'It is said that CHARIZARD''s fire burns hotter if it has experienced harsh battles.',
          'dp3',
          'Secret Wonders',
          'Diamond & Pearl',
          132,
          132,
          '2007/11/01',
          'https://images.pokemontcg.io/dp3/3.png',
          'https://images.pokemontcg.io/dp3/3_hires.png',
          '{6}',
          '{}',
          '[{"name":"Fury Blaze","text":"If your opponent has 3 or less Prize cards left, each of Charizard''s attacks does 50 more damage to the Active Pokémon (before applying Weakness and Resistance).","type":"Poké-Body"}]'::jsonb[],
          '[{"name":"Blast Burn","cost":["Fire","Fire","Fire","Colorless"],"convertedEnergyCost":4,"damage":"120","text":"Flip a coin. If heads, discard 2 Energy cards attached to Charizard. If tails, discard 4 Energy cards attached to Charizard. (If you can''t, this attack does nothing.)"}]'::jsonb[],
          '[{"type":"Water","value":"+40"}]'::jsonb[],
          '[{"type":"Fighting","value":"-20"}]'::jsonb[],
          false,
          false,
          true
        ),
(
          'base1-1',
          'Alakazam',
          'Pokémon',
          '{"Stage 2"}',
          '{"Psychic"}',
          80,
          '{"Colorless","Colorless","Colorless"}',
          '1',
          'Ken Sugimori',
          'Rare Holo',
          'Its brain can outperform a supercomputer. Its intelligence quotient is said to be 5000.',
          'base1',
          'Base',
          'Base',
          102,
          102,
          '1999/01/09',
          'https://images.pokemontcg.io/base1/1.png',
          'https://images.pokemontcg.io/base1/1_hires.png',
          '{65}',
          '{}',
          '[{"name":"Damage Swap","text":"As often as you like during your turn (before your attack), you may move 1 damage counter from 1 of your Pokémon to another as long as you don''t Knock Out that Pokémon. This power can''t be used if Alakazam is Asleep, Confused, or Paralyzed.","type":"Pokémon Power"}]'::jsonb[],
          '[{"name":"Confuse Ray","cost":["Psychic","Psychic","Psychic"],"convertedEnergyCost":3,"damage":"30","text":"Flip a coin. If heads, the Defending Pokémon is now Confused."}]'::jsonb[],
          '[{"type":"Psychic","value":"×2"}]'::jsonb[],
          '[]'::jsonb[],
          false,
          false,
          true
        ),
(
          'ex8-1',
          'Altaria',
          'Pokémon',
          '{"Stage 1"}',
          '{"Colorless"}',
          70,
          '{"Colorless"}',
          '1',
          'Kyoko Umemoto',
          'Rare Holo',
          NULL,
          'ex8',
          'Deoxys',
          'EX',
          107,
          108,
          '2005/02/01',
          'https://images.pokemontcg.io/ex8/1.png',
          'https://images.pokemontcg.io/ex8/1_hires.png',
          '{334}',
          '{}',
          '[{"name":"Safeguard","text":"Prevent all effects of attacks, including damage, done to Altaria by your opponent''s Pokémon-ex.","type":"Poké-Body"}]'::jsonb[],
          '[{"name":"Double Wing Attack","cost":["Lightning"],"convertedEnergyCost":1,"damage":"","text":"Does 20 Damage to each Defending Pokémon."},{"name":"Dive","cost":["Water","Colorless","Colorless"],"convertedEnergyCost":3,"damage":"50","text":""}]'::jsonb[],
          '[{"type":"Lightning","value":"×2"}]'::jsonb[],
          '[{"type":"Fighting","value":"-30"}]'::jsonb[],
          false,
          false,
          true
        ),
(
          'pop5-1',
          'Ho-Oh',
          'Pokémon',
          '{"Basic"}',
          '{"Fire"}',
          80,
          '{"Colorless","Colorless"}',
          '1',
          'Mitsuhiro Arita',
          'Rare',
          NULL,
          'pop5',
          'POP Series 5',
          'POP',
          17,
          17,
          '2007/03/01',
          'https://images.pokemontcg.io/pop5/1.png',
          'https://images.pokemontcg.io/pop5/1_hires.png',
          '{250}',
          '{}',
          '[]'::jsonb[],
          '[{"name":"Fire Wing","cost":["Fire","Colorless"],"convertedEnergyCost":2,"damage":"20","text":""},{"name":"Fire Blast","cost":["Fire","Fire","Fire","Colorless"],"convertedEnergyCost":4,"damage":"60","text":"Discard a Fire Energy attached to Ho-Oh."}]'::jsonb[],
          '[{"type":"Water","value":"×2"}]'::jsonb[],
          '[]'::jsonb[],
          false,
          false,
          true
        ),
(
          'xy10-1',
          'Shuckle',
          'Pokémon',
          '{"Basic"}',
          '{"Grass"}',
          80,
          '{"Colorless"}',
          '1',
          'sui',
          'Uncommon',
          'It stores Berries inside its shell. To avoid attacks, it hides beneath rocks and remains completely still.',
          'xy10',
          'Fates Collide',
          'XY',
          124,
          129,
          '2016/05/02',
          'https://images.pokemontcg.io/xy10/1.png',
          'https://images.pokemontcg.io/xy10/1_hires.png',
          '{213}',
          '{}',
          '[]'::jsonb[],
          '[{"name":"Hide a Berry","cost":["Colorless"],"convertedEnergyCost":1,"damage":"","text":"Draw 2 cards. Then, put a card from your hand on the bottom of your deck."},{"name":"Wrap","cost":["Colorless","Colorless"],"convertedEnergyCost":2,"damage":"30","text":"Flip a coin. If heads, your opponent''s Active Pokémon is now Paralyzed."}]'::jsonb[],
          '[{"type":"Fire","value":"×2"}]'::jsonb[],
          '[]'::jsonb[],
          false,
          true,
          true
        ),
(
          'ecard2-H1',
          'Ampharos',
          'Pokémon',
          '{"Stage 2"}',
          '{"Lightning"}',
          100,
          '{"Colorless","Colorless"}',
          'H1',
          'Shin-ichi Yoshida',
          'Rare Holo',
          NULL,
          'ecard2',
          'Aquapolis',
          'E-Card',
          147,
          182,
          '2003/01/15',
          'https://images.pokemontcg.io/ecard2/H1.png',
          'https://images.pokemontcg.io/ecard2/H1_hires.png',
          '{181}',
          '{}',
          '[]'::jsonb[],
          '[{"name":"Thundershock","cost":["Lightning"],"convertedEnergyCost":1,"damage":"20","text":"Flip a coin. If heads, the Defending Pokémon is now Paralyzed."},{"name":"Reflect Energy","cost":["Lightning","Lightning","Colorless"],"convertedEnergyCost":3,"damage":"50","text":"If you have any Benched Pokémon and if there are any basic Energy cards attached to Ampharos, take 1 of those Energy cards and attach it to 1 of those Pokémon."}]'::jsonb[],
          '[{"type":"Fighting","value":"×2"}]'::jsonb[],
          '[]'::jsonb[],
          false,
          false,
          true
        ),
(
          'base4-1',
          'Alakazam',
          'Pokémon',
          '{"Stage 2"}',
          '{"Psychic"}',
          80,
          '{"Colorless","Colorless","Colorless"}',
          '1',
          'Ken Sugimori',
          'Rare Holo',
          'Its brain can outperform a supercomputer. Its intelligence quotient is said to be 5000.',
          'base4',
          'Base Set 2',
          'Base',
          130,
          130,
          '2000/02/24',
          'https://images.pokemontcg.io/base4/1.png',
          'https://images.pokemontcg.io/base4/1_hires.png',
          '{65}',
          '{}',
          '[{"name":"Damage Swap","text":"As often as you like during your turn (before your attack), you may move 1 damage counter from 1 of your Pokémon to another as long as you don''t Knock Out that Pokémon. This power can''t be used if Alakazam is Asleep, Confused, or Paralyzed.","type":"Pokémon Power"}]'::jsonb[],
          '[{"name":"Confuse Ray","cost":["Psychic","Psychic","Psychic"],"convertedEnergyCost":3,"damage":"30","text":"Flip a coin. If heads, the Defending Pokémon is now Confused."}]'::jsonb[],
          '[{"type":"Psychic","value":"×2"}]'::jsonb[],
          '[]'::jsonb[],
          false,
          false,
          true
        ),
(
          'ex11-1',
          'Beedrill δ',
          'Pokémon',
          '{"Stage 2"}',
          '{"Grass","Metal"}',
          90,
          '{}',
          '1',
          'Masakazu Fukuda',
          'Rare Holo',
          NULL,
          'ex11',
          'Delta Species',
          'EX',
          113,
          114,
          '2005/10/31',
          'https://images.pokemontcg.io/ex11/1.png',
          'https://images.pokemontcg.io/ex11/1_hires.png',
          '{15}',
          '{"This Pokémon is both Grass Metal type."}',
          '[{"name":"Final Sting","text":"Once during your turn (before your attack), you may Knock Out Beedrill. If you do, choose 1 of your opponent''s Defending Pokémon. That Pokémon is now Paralyzed and Poisoned. Put 2 damage counters instead of 1 on that Pokémon between turns. This power can''t be used if Beedrill is affected by a Special Condition.","type":"Poké-Power"}]'::jsonb[],
          '[{"name":"Super Slash","cost":["Grass","Metal","Colorless"],"convertedEnergyCost":3,"damage":"50+","text":"If the Defending Pokémon is an Evolved Pokémon, this attack does 50 damage plus 30 more damage."}]'::jsonb[],
          '[{"type":"Fire","value":"×2"}]'::jsonb[],
          '[]'::jsonb[],
          false,
          false,
          true
        ),
(
          'base3-2',
          'Articuno',
          'Pokémon',
          '{"Basic"}',
          '{"Water"}',
          70,
          '{"Colorless","Colorless"}',
          '2',
          'Mitsuhiro Arita',
          'Rare Holo',
          'A legendary bird Pokémon that is said to appear to doomed people who are lost in icy mountains.',
          'base3',
          'Fossil',
          'Base',
          62,
          62,
          '1999/10/10',
          'https://images.pokemontcg.io/base3/2.png',
          'https://images.pokemontcg.io/base3/2_hires.png',
          '{144}',
          '{}',
          '[]'::jsonb[],
          '[{"name":"Freeze Dry","cost":["Water","Water","Water"],"convertedEnergyCost":3,"damage":"30","text":"Flip a coin. If heads, the Defending Pokémon is now Paralyzed."},{"name":"Blizzard","cost":["Water","Water","Water","Water"],"convertedEnergyCost":4,"damage":"50","text":"Flip a coin. If heads, this attack does 10 damage to each of your opponent''s Benched Pokémon. If tails, this attack does 10 damage to each of your own Benched Pokémon. (Don''t apply Weakness and Resistance for Benched Pokémon.)"}]'::jsonb[],
          '[]'::jsonb[],
          '[{"type":"Fighting","value":"-30"}]'::jsonb[],
          false,
          false,
          true
        ),
(
          'gym1-2',
          'Brock''s Rhydon',
          'Pokémon',
          '{"Stage 1"}',
          '{"Fighting"}',
          80,
          '{"Colorless","Colorless","Colorless"}',
          '2',
          'Ken Sugimori',
          'Rare Holo',
          NULL,
          'gym1',
          'Gym Heroes',
          'Gym',
          132,
          132,
          '2000/08/14',
          'https://images.pokemontcg.io/gym1/2.png',
          'https://images.pokemontcg.io/gym1/2_hires.png',
          '{112}',
          '{}',
          '[{"name":"Bench Guard","text":"As long as Brock''s Rhydon is Benched, whenever 1 of your Benched Pokémon is damaged, you may do 10 of that damage to Brock''s Rhydon instead. (If more than 1 of your Benched Pokémon is damaged at the same time, you may use this power once for each of them.)","type":"Pokémon Power"}]'::jsonb[],
          '[{"name":"Lariat","cost":["Fighting","Fighting","Colorless","Colorless"],"convertedEnergyCost":4,"damage":"70","text":"Flip a coin. If tails, this attack does nothing."}]'::jsonb[],
          '[{"type":"Grass","value":"×2"}]'::jsonb[],
          '[{"type":"Lightning","value":"-30"}]'::jsonb[],
          false,
          false,
          true
        ),
(
          'ex14-1',
          'Banette',
          'Pokémon',
          '{"Stage 1"}',
          '{"Psychic"}',
          70,
          '{"Colorless"}',
          '1',
          'Kyoko Umemoto',
          'Rare Holo',
          NULL,
          'ex14',
          'Crystal Guardians',
          'EX',
          100,
          100,
          '2006/08/01',
          'https://images.pokemontcg.io/ex14/1.png',
          'https://images.pokemontcg.io/ex14/1_hires.png',
          '{354}',
          '{}',
          '[{"name":"Safeguard","text":"Prevent all effects of attacks, including damage, done to Banette by your opponent''s Pokémon-ex.","type":"Poké-Body"}]'::jsonb[],
          '[{"name":"Night Murmurs","cost":["Psychic","Colorless"],"convertedEnergyCost":2,"damage":"30","text":"If the Defending Pokémon is a Basic Pokémon, that Pokémon is now Confused."}]'::jsonb[],
          '[{"type":"Darkness","value":"×2"}]'::jsonb[],
          '[{"type":"Fighting","value":"-30"}]'::jsonb[],
          false,
          false,
          true
        ),
(
          'sm115-1',
          'Caterpie',
          'Pokémon',
          '{"Basic"}',
          '{"Grass"}',
          60,
          '{"Colorless"}',
          '1',
          'tetsuya koizumi',
          'Common',
          'Perhaps because it would like to grow up quickly, it has a voracious appetite, eating a hundred leaves a day.',
          'sm115',
          'Hidden Fates',
          'Sun & Moon',
          68,
          69,
          '2019/08/23',
          'https://images.pokemontcg.io/sm115/1.png',
          'https://images.pokemontcg.io/sm115/1_hires.png',
          '{10}',
          '{}',
          '[]'::jsonb[],
          '[{"name":"Tackle","cost":["Grass"],"convertedEnergyCost":1,"damage":"10","text":""}]'::jsonb[],
          '[{"type":"Fire","value":"×2"}]'::jsonb[],
          '[]'::jsonb[],
          false,
          true,
          true
        ),
(
          'col1-1',
          'Clefable',
          'Pokémon',
          '{"Stage 1"}',
          '{"Colorless"}',
          80,
          '{"Colorless"}',
          '1',
          'sui',
          'Rare Holo',
          'With its acute hearing, it can pick up sounds from far away. It usually hides in quiet places.',
          'col1',
          'Call of Legends',
          'HeartGold & SoulSilver',
          95,
          106,
          '2011/02/09',
          'https://images.pokemontcg.io/col1/1.png',
          'https://images.pokemontcg.io/col1/1_hires.png',
          '{36}',
          '{}',
          '[]'::jsonb[],
          '[{"name":"Fairy Power","cost":["Colorless","Colorless"],"convertedEnergyCost":2,"damage":"","text":"Return 1 of your Pokémon and all cards attached to it in your hand."},{"name":"Moon Impact","cost":["Colorless","Colorless"],"convertedEnergyCost":2,"damage":"40","text":""}]'::jsonb[],
          '[{"type":"Fighting","value":"×2"}]'::jsonb[],
          '[]'::jsonb[],
          false,
          false,
          true
        ),
(
          'ex9-1',
          'Blaziken',
          'Pokémon',
          '{"Stage 2"}',
          '{"Fire"}',
          110,
          '{"Colorless","Colorless"}',
          '1',
          'Midori Harada',
          'Rare Holo',
          NULL,
          'ex9',
          'Emerald',
          'EX',
          106,
          107,
          '2005/05/01',
          'https://images.pokemontcg.io/ex9/1.png',
          'https://images.pokemontcg.io/ex9/1_hires.png',
          '{257}',
          '{}',
          '[{"name":"Blaze","text":"As long as Blaziken''s remaining HP is 40 or less, Blaziken does 40 more damage to the Defending Pokémon (before applying Weakness and Resistance).","type":"Poké-Body"}]'::jsonb[],
          '[{"name":"Searing Flame","cost":["Colorless"],"convertedEnergyCost":1,"damage":"10","text":"The Defending Pokémon is now Burned."},{"name":"Damage Burn","cost":["Fire","Fire","Colorless"],"convertedEnergyCost":3,"damage":"50+","text":"If the Defending Pokémon already has any damage counters on it, this attack does 50 damage plus 20 more damage."}]'::jsonb[],
          '[{"type":"Water","value":"×2"}]'::jsonb[],
          '[]'::jsonb[],
          false,
          false,
          true
        ),
(
          'bw10-1',
          'Surskit',
          'Pokémon',
          '{"Basic"}',
          '{"Grass"}',
          50,
          '{"Colorless"}',
          '1',
          'Naoyo Kimura',
          'Common',
          'It appears as if it is skating on water. It draws prey with a sweet scent from the tip of its head.',
          'bw10',
          'Plasma Blast',
          'Black & White',
          101,
          105,
          '2013/08/14',
          'https://images.pokemontcg.io/bw10/1.png',
          'https://images.pokemontcg.io/bw10/1_hires.png',
          '{283}',
          '{}',
          '[]'::jsonb[],
          '[{"name":"Sweet Scent","cost":["Grass"],"convertedEnergyCost":1,"damage":"","text":"Heal 20 damage from 1 of your Pokémon."}]'::jsonb[],
          '[{"type":"Fire","value":"×2"}]'::jsonb[],
          '[]'::jsonb[],
          false,
          true,
          true
        ),
(
          'ex9-2',
          'Deoxys',
          'Pokémon',
          '{"Basic"}',
          '{"Psychic"}',
          70,
          '{"Colorless"}',
          '2',
          'Hironobu Yoshida',
          'Rare Holo',
          NULL,
          'ex9',
          'Emerald',
          'EX',
          106,
          107,
          '2005/05/01',
          'https://images.pokemontcg.io/ex9/2.png',
          'https://images.pokemontcg.io/ex9/2_hires.png',
          '{386}',
          '{}',
          '[{"name":"Form Change","text":"Once during your turn (before your attack), you may search your deck for another Deoxys and switch it with Deoxys. (Any cards attached to Deoxys, damage counters, Special Conditions, and effects on it are now on the new Pokémon.) If you do, put Deoxys on top of your deck. Shuffle your deck afterward. You can''t use more than 1 Form Change Poké-Power each turn.","type":"Poké-Power"}]'::jsonb[],
          '[{"name":"Swift","cost":["Colorless","Colorless"],"convertedEnergyCost":2,"damage":"30","text":"This attack''s damage isn''t affected by Weakness, Resistance, Poké-Power, Poké-Bodies, or any other effects on the Defending Pokémon."}]'::jsonb[],
          '[{"type":"Psychic","value":"×2"}]'::jsonb[],
          '[]'::jsonb[],
          false,
          false,
          true
        ),
(
          'ru1-3',
          'Ninetales',
          'Pokémon',
          '{"Stage 1"}',
          '{"Fire"}',
          90,
          '{"Colorless"}',
          '3',
          'Pokemon Rumble',
          NULL,
          NULL,
          'ru1',
          'Pokémon Rumble',
          'Other',
          16,
          16,
          '2009/12/02',
          'https://images.pokemontcg.io/ru1/3.png',
          'https://images.pokemontcg.io/ru1/3_hires.png',
          '{38}',
          '{}',
          '[]'::jsonb[],
          '[{"name":"Flame Tail","cost":["Fire","Colorless","Colorless"],"convertedEnergyCost":3,"damage":"60","text":""}]'::jsonb[],
          '[{"type":"Water","value":"×2"}]'::jsonb[],
          '[]'::jsonb[],
          false,
          false,
          true
        ),
(
          'xy5-3',
          'Beedrill',
          'Pokémon',
          '{"Stage 2"}',
          '{"Grass"}',
          120,
          '{}',
          '3',
          'Kouki Saitou',
          'Rare',
          'May appear in a swarm. Flies at violent speeds, all the while stabbing with the toxic stinger on its rear.',
          'xy5',
          'Primal Clash',
          'XY',
          160,
          164,
          '2015/02/04',
          'https://images.pokemontcg.io/xy5/3.png',
          'https://images.pokemontcg.io/xy5/3_hires.png',
          '{15}',
          '{}',
          '[]'::jsonb[],
          '[{"name":"Allergic Shock","cost":["Grass"],"convertedEnergyCost":1,"damage":"","text":"During your next turn, if the Defending Pokémon is damaged by an attack, it is Knocked Out."},{"name":"Twineedle","cost":["Grass","Grass"],"convertedEnergyCost":2,"damage":"50×","text":"Flip 2 coins. This attack does 50 damage times the number of heads."}]'::jsonb[],
          '[{"type":"Fire","value":"×2"}]'::jsonb[],
          '[]'::jsonb[],
          false,
          true,
          true
        ),
(
          'pl3-3',
          'Drifblim FB',
          'Pokémon',
          '{"Basic","SP"}',
          '{"Psychic"}',
          80,
          '{"Colorless","Colorless"}',
          '3',
          'Lee HyunJung',
          'Rare Holo',
          NULL,
          'pl3',
          'Supreme Victors',
          'Platinum',
          147,
          153,
          '2009/08/19',
          'https://images.pokemontcg.io/pl3/3.png',
          'https://images.pokemontcg.io/pl3/3_hires.png',
          '{426}',
          '{}',
          '[{"name":"Pump Up","text":"If your opponent has 3 or less Prize cards left, Drifblim FB gets +40 HP.","type":"Poké-Body"}]'::jsonb[],
          '[{"name":"Shadow Ball","cost":["Psychic","Colorless","Colorless"],"convertedEnergyCost":3,"damage":"","text":"Choose 1 of your opponent''s Benched Pokémon. This attack does 40 damage to that Pokémon. Apply Weakness and Resistance."}]'::jsonb[],
          '[{"type":"Darkness","value":"×2"}]'::jsonb[],
          '[{"type":"Colorless","value":"-20"}]'::jsonb[],
          false,
          false,
          true
        ),
(
          'xy7-2',
          'Gloom',
          'Pokémon',
          '{"Stage 1"}',
          '{"Grass"}',
          80,
          '{"Colorless"}',
          '2',
          'Masakazu Fukuda',
          'Uncommon',
          'The honey it drools from its mouth smells so atrocious, it can curl noses more than a mile away.',
          'xy7',
          'Ancient Origins',
          'XY',
          98,
          100,
          '2015/08/12',
          'https://images.pokemontcg.io/xy7/2.png',
          'https://images.pokemontcg.io/xy7/2_hires.png',
          '{44}',
          '{}',
          '[]'::jsonb[],
          '[{"name":"Drool","cost":["Grass","Colorless"],"convertedEnergyCost":2,"damage":"20","text":""}]'::jsonb[],
          '[{"type":"Fire","value":"×2"}]'::jsonb[],
          '[]'::jsonb[],
          false,
          true,
          true
        ),
(
          'bw10-2',
          'Masquerain',
          'Pokémon',
          '{"Stage 1","Team Plasma"}',
          '{"Grass"}',
          80,
          '{"Colorless"}',
          '2',
          '5ban Graphics',
          'Rare',
          'Its antennae have eye patterns on them. Its four wings enable it to hover and fly in any direction.',
          'bw10',
          'Plasma Blast',
          'Black & White',
          101,
          105,
          '2013/08/14',
          'https://images.pokemontcg.io/bw10/2.png',
          'https://images.pokemontcg.io/bw10/2_hires.png',
          '{284}',
          '{}',
          '[{"name":"Tool Reversal","text":"As often as you like during your turn (before your attack), you may put a Pokémon Tool card attached to 1 of your Pokémon into your hand.","type":"Ability"}]'::jsonb[],
          '[{"name":"Bug Bite","cost":["Colorless","Colorless","Colorless"],"convertedEnergyCost":3,"damage":"60","text":""}]'::jsonb[],
          '[{"type":"Fire","value":"×2"}]'::jsonb[],
          '[]'::jsonb[],
          false,
          true,
          true
        ),
(
          'ex12-3',
          'Cradily',
          'Pokémon',
          '{"Stage 2"}',
          '{"Grass"}',
          100,
          '{"Colorless","Colorless"}',
          '3',
          'Hajime Kusajima',
          'Rare Holo',
          NULL,
          'ex12',
          'Legend Maker',
          'EX',
          92,
          93,
          '2006/02/01',
          'https://images.pokemontcg.io/ex12/3.png',
          'https://images.pokemontcg.io/ex12/3_hires.png',
          '{346}',
          '{}',
          '[]'::jsonb[],
          '[{"name":"Devolution Wave","cost":["Colorless","Colorless"],"convertedEnergyCost":2,"damage":"","text":"Count the number of React Energy cards attached to Cradily and choose up to that number of your opponent''s Evolved Pokémon. Remove the highest Stage Evolution card from each of those Pokémon, then have your opponent shuffle those cards into his or her deck."},{"name":"Linear Attack","cost":["Grass","Colorless"],"convertedEnergyCost":2,"damage":"","text":"Choose 1 of your opponent''s Pokémon. This attack does 30 damage to that Pokémon. (Don''t apply Weakness and Resistance for Benched Pokémon.)"},{"name":"Mud Shot","cost":["Colorless","Colorless","Colorless"],"convertedEnergyCost":3,"damage":"50","text":""}]'::jsonb[],
          '[{"type":"Fire","value":"×2"}]'::jsonb[],
          '[]'::jsonb[],
          false,
          false,
          true
        ),
(
          'xy11-2',
          'Tangrowth',
          'Pokémon',
          '{"Stage 1"}',
          '{"Grass"}',
          130,
          '{"Colorless","Colorless","Colorless","Colorless"}',
          '2',
          'kirisAki',
          'Uncommon',
          'Its vines grow so profusely that, in the warm season, you can''t even see its eyes.',
          'xy11',
          'Steam Siege',
          'XY',
          114,
          116,
          '2016/08/03',
          'https://images.pokemontcg.io/xy11/2.png',
          'https://images.pokemontcg.io/xy11/2_hires.png',
          '{465}',
          '{}',
          '[]'::jsonb[],
          '[{"name":"Leaf Storm","cost":["Grass","Grass","Colorless"],"convertedEnergyCost":3,"damage":"80","text":"Heal 40 damage from each of your Grass Pokémon."},{"name":"Flog","cost":["Grass","Grass","Grass","Colorless"],"convertedEnergyCost":4,"damage":"110+","text":"Flip a coin. If heads, this attack does 30 more damage."}]'::jsonb[],
          '[{"type":"Fire","value":"×2"}]'::jsonb[],
          '[]'::jsonb[],
          false,
          true,
          true
        ),
(
          'ex3-3',
          'Crawdaunt',
          'Pokémon',
          '{"Stage 1"}',
          '{"Water"}',
          80,
          '{"Colorless","Colorless"}',
          '3',
          'Hisao Nakamura',
          'Rare Holo',
          NULL,
          'ex3',
          'Dragon',
          'EX',
          97,
          100,
          '2003/11/24',
          'https://images.pokemontcg.io/ex3/3.png',
          'https://images.pokemontcg.io/ex3/3_hires.png',
          '{342}',
          '{}',
          '[{"name":"Power Pinchers","text":"As long as Crawdaunt is your Active Pokémon, when any of your Active Pokémon does damage to the Defending Pokémon, the attack does 10 more damage (before applying Weakness and Resistance).","type":"Poké-Body"}]'::jsonb[],
          '[{"name":"Guillotine","cost":["Water","Colorless","Colorless"],"convertedEnergyCost":3,"damage":"50","text":""}]'::jsonb[],
          '[{"type":"Lightning","value":"×2"}]'::jsonb[],
          '[]'::jsonb[],
          false,
          false,
          true
        ),
(
          'dv1-3',
          'Dragonair',
          'Pokémon',
          '{"Stage 1"}',
          '{"Dragon"}',
          70,
          '{"Colorless","Colorless"}',
          '3',
          'Hajime Kusajima',
          'Rare Holo',
          'If its body takes on an aura, the weather changes instantly. It is said to live in seas and lakes.',
          'dv1',
          'Dragon Vault',
          'Black & White',
          20,
          21,
          '2012/10/05',
          'https://images.pokemontcg.io/dv1/3.png',
          'https://images.pokemontcg.io/dv1/3_hires.png',
          '{148}',
          '{}',
          '[]'::jsonb[],
          '[{"name":"Tail Whap","cost":["Colorless","Colorless"],"convertedEnergyCost":2,"damage":"20","text":""},{"name":"Dragon Pulse","cost":["Grass","Lightning","Colorless"],"convertedEnergyCost":3,"damage":"70","text":"Discard the top card of your deck."}]'::jsonb[],
          '[{"type":"Dragon","value":"×2"}]'::jsonb[],
          '[]'::jsonb[],
          false,
          true,
          true
        ),
(
          'xy4-1',
          'Venonat',
          'Pokémon',
          '{"Basic"}',
          '{"Grass"}',
          60,
          '{"Colorless"}',
          '1',
          'Sumiyoshi Kizuki',
          'Common',
          'Its big eyes are actually clusters of tiny eyes. At night, its kind is drawn by light.',
          'xy4',
          'Phantom Forces',
          'XY',
          119,
          124,
          '2014/11/05',
          'https://images.pokemontcg.io/xy4/1.png',
          'https://images.pokemontcg.io/xy4/1_hires.png',
          '{48}',
          '{}',
          '[]'::jsonb[],
          '[{"name":"Stun Spore","cost":["Grass","Colorless"],"convertedEnergyCost":2,"damage":"20","text":"Flip a coin. If heads, your opponent''s Active Pokémon is now Paralyzed."}]'::jsonb[],
          '[{"type":"Fire","value":"×2"}]'::jsonb[],
          '[]'::jsonb[],
          false,
          true,
          true
        ),
(
          'bw4-1',
          'Pinsir',
          'Pokémon',
          '{"Basic"}',
          '{"Grass"}',
          80,
          '{"Colorless","Colorless"}',
          '1',
          'Masakazu Fukuda',
          'Rare',
          'It grips prey with its pincers until the prey is torn in half. What it can''t tear, it tosses far.',
          'bw4',
          'Next Destinies',
          'Black & White',
          99,
          103,
          '2012/02/08',
          'https://images.pokemontcg.io/bw4/1.png',
          'https://images.pokemontcg.io/bw4/1_hires.png',
          '{127}',
          '{}',
          '[]'::jsonb[],
          '[{"name":"Power Pinch","cost":["Colorless","Colorless"],"convertedEnergyCost":2,"damage":"","text":"Flip 2 coins. For each heads, discard an Energy attached to the Defending Pokémon."},{"name":"Grip and Squeeze","cost":["Grass","Grass","Colorless"],"convertedEnergyCost":3,"damage":"70","text":"The Defending Pokémon can''t retreat during your opponent''s next turn."}]'::jsonb[],
          '[{"type":"Fire","value":"×2"}]'::jsonb[],
          '[]'::jsonb[],
          false,
          true,
          true
        ) ON CONFLICT ("tcgId") DO UPDATE SET name = EXCLUDED.name, hp = EXCLUDED.hp;