[phases.setup]
nixPkgs = ["nodejs-18_x", "pnpm-8_x"]

[phases.install]
dependsOn = ["setup"]
cmds = ["npm install -g corepack@0.24.1 && corepack enable", "pnpm install --frozen-lockfile"]

[phases.build]
dependsOn = ["install"]
cmds = ["pnpm --filter @pokemon-catalog/api build"]

[start]
cmd = "cd apps/api && node --no-deprecation dist/main.js"

[variables]
NODE_ENV = "production"
NODE_OPTIONS = "--no-deprecation"